version: '3.8'

services:
  banking-service:
    build:
      context: .
      dockerfile: Dockerfile # Make sure your Dockerfile is named correctly
    container_name: banking-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev # Optional: Set active Spring profiles, if needed
    networks:
      - banking-network
    restart: always # Ensures the container restarts on failure
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb-data:/home/dynamodb/data
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"

networks:
  banking-network:
    driver: bridge