# DynamoDB Local configuration
aws:
    dynamodb:
        endpoint: http://localhost:8000
    region: us-west-2
    credentials:
        access-key: dummy
        secret-key: dummy
# OAuth2 configuration
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://dev-rlzncnssjvmpcp7r.us.auth0.com/